apiVersion: inference.networking.x-k8s.io/v1alpha1
kind: EndpointPickerConfig
plugins:
  - name: profile
    type: single-profile-handler
  - name: tokenizer
    type: tokenizer
    parameters:
      modelName: Qwen/Qwen3-14B
      udsTokenizerConfig:
        socketFile: /tmp/tokenizer/tokenizer-uds.socket
  - name: ppc
    type: precise-prefix-cache-scorer
    parameters:
      speculativeIndexing: true
      tokenProcessorConfig:
        blockSize: 64
      indexerConfig:
        tokenizersPoolConfig:
          modelName: Qwen/Qwen3-14B
          local: null
          hf: null
          uds:
            socketFile: /tmp/tokenizer/tokenizer-uds.socket
      kvEventsConfig:
        topicFilter: "kv@"
        concurrency: 4
        discoverPods: false
        zmqEndpoint: "tcp://*:5557"
  - name: kv
    type: kv-cache-utilization-scorer
  - name: qd
    type: queue-scorer
  - name: delegation-scorer
    type: adaptive-routing-scorer
    parameters:
      scorerNames: ["ppc", "qd", "kv"]
      baseWeights: [3.0, 2.0, 2.0]
      mode: "adaptive"
  - name: picker
    type: max-score-picker
schedulingProfiles:
  - name: default
    plugins:
      - pluginRef: delegation-scorer
        weight: 1.0
      - pluginRef: picker
